#!/bin/bash

sudo svn up @FINKPREFIX@/fink/dists/macathena/
fink index
fink update `fink list --installed --tab macathena | awk '{ print $2 }' | xargs echo`
echo "All MacAthena packages should have been updated, but you should run fink update-all to make sure you have the latest packages"
