#!/bin/bash

cd /var/db/openafs/etc

rm -f config/afsd.options.old
echo '-afsdb -stat 2000 -dcache 800 -daemons 3 -volumes 70 -dynroot -fakestat-all' > config/afsd.options.old
if cmp -s config/afsd.options.old config/afsd.options ; then
	rm -f config/afsd.options
fi
rm -f config/afsd.options.broken

if [ ! -f config/afs.conf -a -f config/afs.conf.sample ]; then
	cp config/afs.conf.sample config/afs.conf
fi

sudo /Library/StartupItems/OpenAFS/OpenAFS restart
